(function(){
  'use strict';
  const ROUTE_KEY='shelter_pro_route_v5';
  function normaliseId(v){return String(v&&typeof v==='object'?(v.id??v.siteId??''):v??'').trim();}
  function savedRoute(){try{const raw=JSON.parse(localStorage.getItem(ROUTE_KEY)||'[]');return Array.isArray(raw)?raw.map(normaliseId).filter(Boolean):[];}catch(_){return [];}}
  function routeIds(){let ids=[];try{ids=window.ShelterProWorkflow?.getRoute?.()||window.ShelterProState?.getRoute?.()||[];}catch(_){}ids=Array.isArray(ids)?ids.map(normaliseId).filter(Boolean):[];if(!ids.length)ids=savedRoute();return [...new Set(ids)].filter(id=>{const st=typeof window.statusOf==='function'?window.statusOf(id):'none';return st!=='cleaned'&&st!=='skipped';});}
  function sites(){return routeIds().map(id=>window.SITES?.find(s=>String(s.id).toUpperCase()===id.toUpperCase())).filter(Boolean);}
  function appleUrl(stops){if(!stops.length)return'';const final=stops.at(-1),wp=stops.slice(0,-1).map(s=>`${s.lat},${s.lon}`).join('|');let u=`https://maps.apple.com/?daddr=${encodeURIComponent(`${final.lat},${final.lon}`)}&dirflg=d`;if(wp)u+=`&waypoints=${encodeURIComponent(wp)}`;return u;}
  function googleUrl(stops){if(!stops.length)return'';const final=stops.at(-1),wp=stops.slice(0,-1).map(s=>`${s.lat},${s.lon}`).join('|');let u=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${final.lat},${final.lon}`)}&travelmode=driving`;if(wp)u+=`&waypoints=${encodeURIComponent(wp)}`;return u;}
  function text(stops){return stops.map((s,i)=>`${i+1}. Site ${s.id} - ${s.address||`${s.lat}, ${s.lon}`}`).join('\n');}
  function open(){const stops=sites();if(!stops.length){alert('There is no active route to share. Add stops in Route Manager first.');return;}document.getElementById('routeShareList').innerHTML=stops.map(s=>`<li><strong>Site ${s.id}</strong><br><span>${s.address||''}</span></li>`).join('');document.getElementById('routeShareCount').textContent=`${stops.length} remaining stop${stops.length===1?'':'s'}`;document.getElementById('routeShareModal').classList.add('open');}
  function close(){document.getElementById('routeShareModal')?.classList.remove('open');}
  function wireButtons(){for(const id of ['shareActiveRoute','routeShareFromManager']){const b=document.getElementById(id);if(b&&!b.dataset.routeShareWired){b.dataset.routeShareWired='1';b.addEventListener('click',open);}}}
  function install(){if(!document.getElementById('routeShareModal'))document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop route-share-modal" id="routeShareModal" role="dialog" aria-modal="true"><div class="settings-card route-share-card"><h2>Share Active Route</h2><p id="routeShareCount"></p><ol class="route-share-list" id="routeShareList"></ol><div class="route-share-actions"><button class="primary" id="routeShareApple">🍎 Open Route in Apple Maps</button><button id="routeShareGoogle">🌍 Open Route in Google Maps</button><button id="routeShareCopy">📋 Copy Route List</button></div><button id="routeShareClose">Cancel</button></div></div>`);wireButtons();new MutationObserver(wireButtons).observe(document.body,{childList:true,subtree:true});document.getElementById('routeShareClose').onclick=close;document.getElementById('routeShareModal').onclick=e=>{if(e.target.id==='routeShareModal')close();};document.getElementById('routeShareApple').onclick=()=>{const u=appleUrl(sites());if(u)location.href=u;};document.getElementById('routeShareGoogle').onclick=()=>{const s=sites();if(s.length>10)alert('Google Maps will open the first 10 remaining stops.');const u=googleUrl(s.slice(0,10));if(u)window.open(u,'_blank','noopener');};document.getElementById('routeShareCopy').onclick=async()=>{const t=text(sites());if(!t)return;try{await navigator.clipboard.writeText(t);alert('Active route copied.');}catch(_){prompt('Copy active route:',t);}};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
  window.ShelterProRouteShare={open,getRouteIds:routeIds};
})();
